apiVersion: v1
kind: Service
metadata:
  name: simpletimeservice-service
spec:
  selector:
    app: simpletimeservice
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  clusterIP: None  # Do not use LoadBalancer
