apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpletimeservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpletimeservice
  template:
    metadata:
      labels:
        app: simpletimeservice
    spec:
      containers:
        - name: simpletimeservice
          image: hetdesai08/simpletimeservice:latest
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
